/***
 * Lockstep Platform SDK for C#
 *
 * (c) 2021-2025 Lockstep, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     Lockstep Network <support@lockstep.io>
 * @copyright  2021-2025 Lockstep, Inc.
 * @link       https://github.com/Lockstep-Network/lockstep-sdk-csharp
 */



using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using LockstepSDK.Models;


namespace LockstepSDK.Clients
{
    /// <summary>
    /// API methods related to Payments
    /// </summary>
    public class PaymentsClient
    {
        private readonly LockstepApi _client;

        /// <summary>
        /// Constructor
        /// </summary>
        public PaymentsClient(LockstepApi client)
        {
            _client = client;
        }

        /// <summary>
        /// Retrieves the Payment specified by this unique identifier, optionally including nested data sets.
        ///
        /// A Payment represents money sent from one company to another.  A single payment may contain payments for one or more invoices; it is also possible for payments to be made in advance of an invoice, for example, as a deposit.  The creator of the Payment is identified by the `CustomerId` field, and the recipient of the Payment is identified by the `CompanyId` field.  Most Payments are uniquely identified both by a ADS Platform ID number and a customer ERP &quot;key&quot; that was generated by the system that originated the Payment.  Payments that have not been fully applied have a nonzero `UnappliedAmount` value, which represents a deposit that has been paid and not yet applied to an Invoice.
        ///
        /// </summary>
        /// <param name="id">The unique ADS Platform ID number of this Payment; NOT the customer's ERP key</param>
        /// <param name="include">To fetch additional data on this object, specify the list of elements to retrieve. Available collections: Applications, Notes, Attachments, CustomFields</param>
        public async Task<LockstepResponse<PaymentModel>> RetrievePayment(Guid id, string include = null)
        {
            var url = $"/api/v1/Payments/{id}";
            var options = new Dictionary<string, object>();
            if (include != null) { options["include"] = include; }
            return await _client.Request<PaymentModel>(HttpMethod.Get, url, options, null, null);
        }

        /// <summary>
        /// Updates an existing Payment with the information supplied to this PATCH call.
        ///
        /// The PATCH method allows you to change specific values on the object while leaving other values alone.  As input you should supply a list of field names and new values.  If you do not provide the name of a field, that field will remain unchanged.  This allows you to ensure that you are only updating the specific fields desired.
        ///
        /// A Payment represents money sent from one company to another.  A single payment may contain payments for one or more invoices; it is also possible for payments to be made in advance of an invoice, for example, as a deposit.  The creator of the Payment is identified by the `CustomerId` field, and the recipient of the Payment is identified by the `CompanyId` field.  Most Payments are uniquely identified both by a ADS Platform ID number and a customer ERP &quot;key&quot; that was generated by the system that originated the Payment.  Payments that have not been fully applied have a nonzero `UnappliedAmount` value, which represents a deposit that has been paid and not yet applied to an Invoice.
        ///
        /// </summary>
        /// <param name="id">The unique ADS Platform ID number of the Payment to update; NOT the customer's ERP key</param>
        /// <param name="body">A list of changes to apply to this Payment</param>
        public async Task<LockstepResponse<PaymentModel>> UpdatePayment(Guid id, object body)
        {
            var url = $"/api/v1/Payments/{id}";
            return await _client.Request<PaymentModel>(new HttpMethod("PATCH"), url, null, body, null);
        }

        /// <summary>
        /// Deletes the Payment referred to by this unique identifier.
        ///
        /// A Payment represents money sent from one company to another.  A single payment may contain payments for one or more invoices; it is also possible for payments to be made in advance of an invoice, for example, as a deposit.  The creator of the Payment is identified by the `CustomerId` field, and the recipient of the Payment is identified by the `CompanyId` field.  Most Payments are uniquely identified both by a ADS Platform ID number and a customer ERP &quot;key&quot; that was generated by the system that originated the Payment.  Payments that have not been fully applied have a nonzero `UnappliedAmount` value, which represents a deposit that has been paid and not yet applied to an Invoice.
        ///
        /// </summary>
        /// <param name="id">The unique ADS Platform ID number of the Payment to delete; NOT the customer's ERP key</param>
        public async Task<LockstepResponse<ActionResultModel>> DeletePayment(Guid id)
        {
            var url = $"/api/v1/Payments/{id}";
            return await _client.Request<ActionResultModel>(HttpMethod.Delete, url, null, null, null);
        }

        /// <summary>
        /// Creates one or more Payments within this account and returns the records as created.
        ///
        /// A Payment represents money sent from one company to another.  A single payment may contain payments for one or more invoices; it is also possible for payments to be made in advance of an invoice, for example, as a deposit.  The creator of the Payment is identified by the `CustomerId` field, and the recipient of the Payment is identified by the `CompanyId` field.  Most Payments are uniquely identified both by a ADS Platform ID number and a customer ERP &quot;key&quot; that was generated by the system that originated the Payment.  Payments that have not been fully applied have a nonzero `UnappliedAmount` value, which represents a deposit that has been paid and not yet applied to an Invoice.
        ///
        /// </summary>
        /// <param name="body">The Payments to create</param>
        public async Task<LockstepResponse<PaymentModel[]>> CreatePayments(PaymentModel[] body)
        {
            var url = $"/api/v1/Payments";
            return await _client.Request<PaymentModel[]>(HttpMethod.Post, url, null, body, null);
        }

        /// <summary>
        /// Queries Payments for this account using the specified filtering, sorting, nested fetch, and pagination rules requested.
        ///
        /// More information on querying can be found on the [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight) page on the ADS Platform Developer website.
        ///
        /// A Payment represents money sent from one company to another.  A single payment may contain payments for one or more invoices; it is also possible for payments to be made in advance of an invoice, for example, as a deposit.  The creator of the Payment is identified by the `CustomerId` field, and the recipient of the Payment is identified by the `CompanyId` field.  Most Payments are uniquely identified both by a ADS Platform ID number and a customer ERP &quot;key&quot; that was generated by the system that originated the Payment.  Payments that have not been fully applied have a nonzero `UnappliedAmount` value, which represents a deposit that has been paid and not yet applied to an Invoice.
        ///
        /// </summary>
        /// <param name="filter">The filter for this query. See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)</param>
        /// <param name="include">To fetch additional data on this object, specify the list of elements to retrieve. Available collections: Applications, Notes, Attachments, CustomFields</param>
        /// <param name="order">The sort order for this query. See See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)</param>
        /// <param name="pageSize">The page size for results (default 250, maximum of 500). See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)</param>
        /// <param name="pageNumber">The page number for results (default 0). See [Searchlight Query Language](https://developer.lockstep.io/docs/querying-with-searchlight)</param>
        public async Task<LockstepResponse<FetchResult<PaymentModel>>> QueryPayments(string filter = null, string include = null, string order = null, int? pageSize = null, int? pageNumber = null)
        {
            var url = $"/api/v1/Payments/query";
            var options = new Dictionary<string, object>();
            if (filter != null) { options["filter"] = filter; }
            if (include != null) { options["include"] = include; }
            if (order != null) { options["order"] = order; }
            if (pageSize != null) { options["pageSize"] = pageSize; }
            if (pageNumber != null) { options["pageNumber"] = pageNumber; }
            return await _client.Request<FetchResult<PaymentModel>>(HttpMethod.Get, url, options, null, null);
        }

        /// <summary>
        /// Retrieves a PDF file for this payment if it has been synced using an app enrollment to one of the supported apps.
        ///
        /// QuickBooks Online supports AR Payments.
        ///
        /// For other ERPs, the supported types will depend on the synced data.
        ///
        /// </summary>
        /// <param name="id">The unique ADS Platform ID number of this payment; NOT the customer's ERP key</param>
        public async Task<LockstepResponse<byte[]>> RetrievepaymentPDF(Guid id)
        {
            var url = $"/api/v1/Payments/{id}/pdf";
            return await _client.Request<byte[]>(HttpMethod.Get, url, null, null, null);
        }

        /// <summary>
        /// Checks for whether a PDF file for this payment exists if it has been synced using an app enrollment to one of the supported apps.
        ///
        /// QuickBooks Online supports AR Payments.
        ///
        /// For other ERPs, the supported types will depend on the synced data.
        ///
        /// </summary>
        /// <param name="id">The unique ADS Platform ID number of this payment; NOT the customer's ERP key</param>
        public async Task<LockstepResponse<byte[]>> CheckpaymentPDF(Guid id)
        {
            var url = $"/api/v1/Payments/{id}/pdf";
            return await _client.Request<byte[]>(HttpMethod.Head, url, null, null, null);
        }
    }
}
