/***
 * Lockstep Platform SDK for C#
 *
 * (c) 2021-2023 Lockstep, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     Lockstep Network <support@lockstep.io>
 * @copyright  2021-2023 Lockstep, Inc.
 * @link       https://github.com/Lockstep-Network/lockstep-sdk-csharp
 */



#pragma warning disable CS8618

using System;

namespace LockstepSDK.Models
{

    /// <summary>
    /// Represents the email reply suggestion from the SAGE GMS API
    /// </summary>
    public class EmailReplyGeneratorSuggestions
    {

        /// <summary>
        /// The kind of reply generated by the GMS Api
        /// </summary>
        public string Kind { get; set; }

        /// <summary>
        /// The body of the reply generated by the GMS Api
        /// </summary>
        public string Body { get; set; }
    }
}
