/***
 * Lockstep Platform SDK for C#
 *
 * (c) 2021-2025 Lockstep, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     Lockstep Network <support@lockstep.io>
 * @copyright  2021-2025 Lockstep, Inc.
 * @link       https://github.com/Lockstep-Network/lockstep-sdk-csharp
 */



#pragma warning disable CS8618

using System;

namespace LockstepSDK.Models
{

    /// <summary>
    /// Represents transaction detail information associated to a transaction. This can either be Invoices which are paid with a
    /// Credit Memo or Payment transaction, or Credit Memos or Payments used as payment for an Invoice transaction.
    /// </summary>
    public class TransactionDetailModel
    {

        /// <summary>
        /// Group account transaction detail is associated with.
        /// </summary>
        public Guid? GroupKey { get; set; }

        /// <summary>
        /// The base currency code of the group.
        /// </summary>
        public string BaseCurrencyCode { get; set; }

        /// <summary>
        /// An additional reference number that is sometimes used to identify a transaction detail.
        /// The meaning of this field is specific to the ERP or accounting system used by the user.
        /// </summary>
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// The unique ID of the transaction detail record.
        /// </summary>
        public Guid? TransactionDetailId { get; set; }

        /// <summary>
        /// The unique ID of the entity applying the transaction to the transaction detail record.
        /// </summary>
        public Guid? TransactionDetailAppliedId { get; set; }

        /// <summary>
        /// The unique ID of the transaction record.
        /// </summary>
        public Guid? TransactionId { get; set; }

        /// <summary>
        /// The type of the transaction detail record.
        ///
        /// Recognized Invoice types are:
        /// * `AR Invoice` - Represents an invoice sent by Company to the Customer
        /// * `AP Invoice` - Represents an invoice sent by Vendor to the Company
        /// * `AR Credit Memo` - Represents a credit memo generated by Company given to Customer
        /// * `AP Credit Memo` - Represents a credit memo generated by Vendor given to Company
        ///
        /// Recognized PaymentType values are:
        /// * `AR Payment` - A payment made by a Customer to the Company
        /// * `AP Payment` - A payment made by the Company to a Vendor
        /// </summary>
        public string TransactionType { get; set; }

        /// <summary>
        /// Additional type categorization of the transaction.
        /// </summary>
        public string TransactionSubType { get; set; }

        /// <summary>
        /// The date when a transaction detail record was reported.
        /// </summary>
        public DateTime? TransactionDate { get; set; }

        /// <summary>
        /// The date of the invoice associated to the transaction detail record.
        /// </summary>
        public DateTime? TransactionInvoiceDate { get; set; }

        /// <summary>
        /// The currency code of the transaction.
        /// </summary>
        public string CurrencyCode { get; set; }

        /// <summary>
        /// The total value of this transaction detail, inclusive or all taxes and line items.
        /// </summary>
        public decimal? TransactionAmount { get; set; }

        /// <summary>
        /// The remaining balance of this transaction detail.
        /// </summary>
        public decimal? OutstandingAmount { get; set; }

        /// <summary>
        /// The total value of this transaction detail, inclusive or all taxes and line items in the group&#39;s base currency.
        /// </summary>
        public decimal? BaseCurrencyTransactionAmount { get; set; }

        /// <summary>
        /// The remaining balance of this transaction detail in the group&#39;s base currency.
        /// </summary>
        public decimal? BaseCurrencyOutstandingAmount { get; set; }

        /// <summary>
        /// Specific transactions have support for pdf retrieval from their respective erp. When this flag is true, an additional
        /// call to Invoices/{id}/pdf or Payments/{id}/pdf can be made to retrieve a pdf directly from the erp.
        /// </summary>
        public bool? SupportsErpPdfRetrieval { get; set; }

        /// <summary>
        /// Specific payment transactions have a status with Service Fabric.
        ///
        /// Recognized values are:
        /// * PENDING
        /// * PAID
        /// * PAID_OFFLINE
        /// * PARTIALLY
        /// * PARTIALLY_REFUNDED
        /// </summary>
        public string ServiceFabricStatus { get; set; }
    }
}
