name: NuGet Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Build solution and generate NuGet package
        run: dotnet build -c Release

      - name: Run Nuget pack
        run: dotnet pack -c Release -p:Nuspecfile=../LockstepApi.nuspec --output artifacts

      - name: Upload Nuget package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: 'artifacts/*.nupkg'

      - name: Push generated package to GitHub registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: dotnet nuget push artifacts/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
